[project]
name = "langbot"
version = "0.2.0"
description = ""
authors = [{ name = "EcmaXp", email = "ecmaxp@ecmaxp.kr" }]
requires-python = ">=3.12"
dependencies = [
    "async-lru>=2.0.4",
    "hikari[speedups]>=2.0.0",
    "langchain>=0.3.0",
    "langchain-anthropic>=0.2.0",
    "langchain-community>=0.3.0",
    "langchain-core>=0.3.0",
    "langchain-google-genai>=2.0.0",
    "langchain-openai>=0.2.0",
    "pillow>=10.4.0",
    "pydantic>=2.9.1",
    "pydantic-settings>=2.5.2",
    "transformers>=4.44.2",
    "uvloop>=0.20.0",
    "tokencost>=0.1.12",
]

[tool.uv]
dev-dependencies = [
    "reloader-py>=0.15.0",
]

[project.scripts]
langbot = "langbot.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["langbot"]

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle (error)
    "F",   # pyflakes
    "B",   # bugbear
    "C4",  # flake8-comprehensions
    "SIM", # flake8-simplify
    "I",   # isort
    "UP",  # pyupgrade
    "PIE", # flake8-pie
    "PGH", # pygrep-hooks
    "PYI", # flake8-pyi
    "RUF", # Ruff-specific rules
]

ignore = [
    "E501", # line-too-long
]
