[tool.poetry]
name = "langbot"
version = "0.1.0"
description = ""
authors = ["ecmaxp <ecmaxp@ecmaxp.kr>"]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
hikari = {extras = ["speedups"], version = "^2.0.0.dev123"}
langchain = "^0.1.14"
langchain-core = "^0.1.40"
langchain-community = "^0.0.31"
langchain-openai = "^0.1.1"
uvloop = "^0.19.0"
async-lru = "^2.0.4"

[tool.poetry.group.dev.dependencies]
"reloader.py" = "^0.12.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
