apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: langbot-gpt-4o
  namespace: langbot
  labels:
    app: langbot
    model: gpt-4o
spec:
  serviceName: langbot-gpt-4o
  replicas: 1
  selector:
    matchLabels:
      app: langbot
      model: gpt-4o
  template:
    metadata:
      labels:
        app: langbot
        model: gpt-4o
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: langbot
          image: registry-prod.deer-neon.ts.net/langbot:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 512M
            limits:
              cpu: 1000m
              memory: 512M
          env:
            - name: LANGBOT_CHAT_MODEL
              value: "openai:gpt-4o-2024-08-06"
            - name: LANGBOT_POLICY__ALLOWED_IMAGE_MODELS
              value: '["gpt-4o-2024-08-06"]'
          envFrom:
            - configMapRef:
                name: langbot-policy
              prefix: LANGBOT_POLICY__
            - secretRef:
                name: langbot-secret-gpt-4o
---
