apiVersion: apps/v1
kind: Deployment
metadata:
  name: langbot-gemini-pro
  namespace: langbot
  labels:
    app: langbot
    model: gemini-pro-2-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langbot
      model: gemini-pro-2-5
  template:
    metadata:
      labels:
        app: langbot
        model: gemini-pro-2-5
    spec:
      serviceAccountName: langbot
      terminationGracePeriodSeconds: 5
      containers:
        - name: langbot
          image: registry-prod.deer-neon.ts.net/langbot:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 250M
            limits:
              cpu: 1000m
              memory: 250M
          env:
            - name: LANGBOT_CHAT_MODEL
              value: "gemini/gemini-2.5-pro"
          envFrom:
            - configMapRef:
                name: langbot-policy
              prefix: LANGBOT_POLICY__
            - secretRef:
                name: langbot-openai
            - secretRef:
                name: langbot-gemini-pro
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: langbot-gemini-pro
  namespace: langbot
spec:
  vaultAuthRef: langbot
  mount: op
  path: vaults/sigsrv-prod/items/sigsrv-prod-langbot-secrets-gemini
  refreshAfter: 60s
  destination:
    create: true
    name: langbot-gemini-pro
    transformation:
      includes:
        - LANGBOT_DISCORD_TOKEN
        - GEMINI_API_KEY
