apiVersion: apps/v1
kind: Deployment
metadata:
  name: langbot-openai-gpt
  namespace: langbot
  labels:
    app: langbot
    model: gpt-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langbot
      model: gpt-5
  template:
    metadata:
      labels:
        app: langbot
        model: gpt-5
    spec:
      serviceAccountName: langbot
      terminationGracePeriodSeconds: 5
      containers:
        - name: langbot
          image: registry-prod.deer-neon.ts.net/langbot:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 250M
            limits:
              cpu: 1000m
              memory: 250M
          env:
            - name: LANGBOT_CHAT_MODEL
              value: "gpt-5-chat-latest"
            - name: LANGBOT_POLICY__ALLOWED_IMAGE_MODELS
              value: '["gpt-5-chat-latest"]'
          envFrom:
            - configMapRef:
                name: langbot-policy
              prefix: LANGBOT_POLICY__
            - secretRef:
                name: langbot-openai
            - secretRef:
                name: langbot-openai-gpt
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: langbot-openai-gpt
  namespace: langbot
spec:
  vaultAuthRef: langbot
  mount: op
  path: vaults/sigsrv-prod/items/sigsrv-prod-langbot-secrets-openai-gpt-4
  refreshAfter: 60s
  destination:
    create: true
    name: langbot-openai-gpt
    transformation:
      includes:
        - LANGBOT_DISCORD_TOKEN
