apiVersion: v1
kind: ConfigMap
metadata:
  name: langbot-policy
  namespace: langbot
  labels:
    app: langbot
data:
  INPUT_TOKEN_LIMIT: "64KB"
  OUTPUT_TOKEN_LIMIT: "32KB"
  MAX_TEXT_FILE_SIZE: "32KB"
