apiVersion: apps/v1
kind: Deployment
metadata:
  name: langbot-gemini
  namespace: langbot
  labels:
    app: langbot
    model: gemini-2-5-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langbot
      model: gemini-2-5-pro
  template:
    metadata:
      labels:
        app: langbot
        model: gemini-2-5-pro
    spec:
      serviceAccountName: langbot
      terminationGracePeriodSeconds: 5
      containers:
        - name: langbot
          image: registry-prod.deer-neon.ts.net/langbot:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 200M
            limits:
              cpu: 1000m
              memory: 200M
          env:
            - name: LANGBOT_CHAT_MODEL
              value: "google-genai:gemini-2.5-pro-preview-03-25"
          envFrom:
            - configMapRef:
                name: langbot-policy
              prefix: LANGBOT_POLICY__
            - configMapRef:
                name: langbot-gemini-fallback
              prefix: LANGBOT_FALLBACK__
            - secretRef:
                name: langbot-openai
            - secretRef:
                name: langbot-gemini
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: langbot-gemini
  namespace: langbot
spec:
  vaultAuthRef: langbot
  mount: op
  path: vaults/sigsrv-prod/items/sigsrv-prod-langbot-secrets-gemini
  refreshAfter: 60s
  destination:
    create: true
    name: langbot-gemini
    transformation:
      includes:
        - LANGBOT_DISCORD_TOKEN
        - GOOGLE_API_KEY
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: langbot-gemini-fallback
  namespace: langbot
  labels:
    app: langbot
data:
  OVERRIDE_COSTS: "true"
  INPUT_COST_PER_TOKEN: "0"
  OUTPUT_COST_PER_TOKEN: "0"
