apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: langbot-gpt-35
  namespace: langbot
  labels:
    app: langbot
    model: gpt-3.5-turbo
spec:
  serviceName: langbot-gpt-35
  replicas: 1
  selector:
    matchLabels:
      app: langbot
      model: gpt-3.5-turbo
  template:
    metadata:
      labels:
        app: langbot
        model: gpt-3.5-turbo
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: langbot
          image: registry-prod.deer-neon.ts.net/langbot:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 512M
            limits:
              cpu: 1000m
              memory: 512M
          env:
            - name: LANGBOT_CHAT_MODEL
              value: "openai:gpt-3.5-turbo-0125"
          envFrom:
            - secretRef:
                name: langbot-secret-gpt-35
---
