apiVersion: apps/v1
kind: Deployment
metadata:
  name: langbot-claude-sonnet
  namespace: langbot
  labels:
    app: langbot
    model: claude-sonnet-4-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langbot
      model: claude-sonnet-4-5
  template:
    metadata:
      labels:
        app: langbot
        model: claude-sonnet-4-5
    spec:
      serviceAccountName: langbot
      terminationGracePeriodSeconds: 5
      containers:
        - name: langbot
          image: registry-prod.deer-neon.ts.net/langbot:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 250M
            limits:
              cpu: 1000m
              memory: 250M
          env:
            - name: LANGBOT_CHAT_MODEL
              value: "claude-sonnet-4-5-20250929"
          envFrom:
            - configMapRef:
                name: langbot-policy
              prefix: LANGBOT_POLICY__
            - configMapRef:
                name: langbot-claude-sonnet-fallback
              prefix: LANGBOT_FALLBACK__
            - secretRef:
                name: langbot-openai
            - secretRef:
                name: langbot-claude-sonnet
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: langbot-claude-sonnet
  namespace: langbot
spec:
  vaultAuthRef: langbot
  mount: op
  path: vaults/sigsrv-prod/items/sigsrv-prod-langbot-secrets-claude
  refreshAfter: 60s
  destination:
    create: true
    name: langbot-claude-sonnet
    transformation:
      includes:
        - LANGBOT_DISCORD_TOKEN
        - ANTHROPIC_API_KEY
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: langbot-claude-sonnet-fallback
  namespace: langbot
  labels:
    app: langbot
data:
  OVERRIDE_COSTS: "true"
  COST_MODEL_NAME: "claude-4-sonnet-20250514"
